### ISSUE TITLE
Send command to running container?

### ISSUE THREAD

**Issue by xtwist** [clue/docker-psocksd#2]
Hello!
How to send a command (for example via default xx.xx.xx.xx) to container?
I tried to do that via docker exec, but didn't succeed.

**Comment by clue** [comment]
Hi @yuriylevin93! psocksd accepts commands via STDIN, so you may want to try starting it in interactive mode like this:

``` bash
$ docker run -it --rm -p 9050:9050 clue/psocksd
use direct connection to target
SOCKS proxy server listening on 0.0.0.0:9050

> via default 1.2.3.4:9050
use socks://1.2.3.4:9050 as next hop (resolve remotely)

> quit
exiting...
```

I hope this helps!
